version: "2"
services:

  teslalogger:
    build: docker/teslalogger/.
    restart: always
    volumes:
      - /mnt/data/supervisor/share/TeslaLogger/www:/var/www/html
      - /mnt/data/supervisor/share/TeslaLogger/bin:/etc/teslalogger
      - /mnt/data/supervisor/share/TeslaLogger/GrafanaDashboards/:/var/lib/grafana/dashboards/
      - /mnt/data/supervisor/share/TeslaLogger/GrafanaPlugins/:/var/lib/grafana/plugins
      - /mnt/data/supervisor/share/docker/teslalogger/Dockerfile:/tmp/teslalogger-DOCKER
      - /mnt/data/supervisor/share/teslalogger-tmp:/tmp/
    depends_on:
      - database
    environment:
      - TZ=Europe/Berlin

  database:
    image: mariadb:10.4.7
    restart: always
    env_file:
      - .env
    volumes:
      - /mnt/data/supervisor/share./TeslaLogger/sqlschema.sql:/docker-entrypoint-initdb.d/sqlschema.sql
    ports:
      - 3306:3306
    environment:
      - TZ=Europe/Berlin

  grafana:
    image: grafana/grafana:7.2.0
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=teslalogger
      - TZ=Europe/Berlin
    ports:
      - 3000:3000
    volumes:
      - /mnt/data/supervisor/share/TeslaLogger/bin:/etc/teslalogger
      - /mnt/data/supervisor/share/TeslaLogger/GrafanaDashboards/:/var/lib/grafana/dashboards/
      - /mnt/data/supervisor/share/TeslaLogger/GrafanaPlugins/:/var/lib/grafana/plugins
      - /mnt/data/supervisor/share/TeslaLogger/GrafanaConfig/:/etc/grafana/provisioning/datasources/
      #- /mnt/data/supervisor/share/TeslaLogger/GrafanaConfig/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml
      #- /mnt/data/supervisor/share/TeslaLogger/GrafanaConfig/sample.yaml:/etc/grafana/provisioning/dashboards/dashboards.yml
    depends_on:
      - database

  webserver:
    build: docker/webserver/.
    restart: always
    volumes:
      - /mnt/data/supervisor/share/docker/webserver/php.ini:/usr/local/etc/php/php.ini
      - /mnt/data/supervisor/share/TeslaLogger/www:/var/www/html
      - /mnt/data/supervisor/share/TeslaLogger/bin:/etc/teslalogger
      - /mnt/data/supervisor/share/docker/teslalogger/Dockerfile:/tmp/teslalogger-DOCKER
      - /mnt/data/supervisor/share/teslalogger-tmp:/tmp/
    ports:
      - 8888:80
    environment:
      - TZ=Europe/Berlin

#volumes:
    #teslalogger-tmp:
        #driver: local
        #driver_opts:
            #type: 'none'
            #o: 'bind'
            #device: '/mnt/data/supervisor/share/teslalogger-tmp'
